### PR TITLE
Input case preservation and BCP-47 support

### PR DESCRIPTION
**Pull request by pond**
* Resolves an issue when using Rails and `I18n.locale = ...`. Returned values were always coerced to lower case. Using `two_letter_truncate: false` would result in e.g. `en-NZ` being turned into `en-nz`. Rails unfortunately has a case-sensitive matching strategy (https://github.com/svenfuchs/rails-i18n/issues/282) so this would result in an I18n exception. This PR allows the case of the input list of available languages to be preserved.

* In case someone does want normalisation, proper BCP 47 normalisation (as best I can fathom it!) is also implemented as an option.

* Test coverage included, `README.md` updated.

### CODE REVIEW

**Comment by pond** [comment]
NB I'm not going to spend time pandering to Rubocop complaining that a method implementing complex RFC rules is complex and has many lines. If someone else wants to make the code actually _harder_ to read and follow by splitting things like that up into single-use methods that force the reader to jump around the code base, well, fair enough.

**Comment by cyril** [comment]
Thank you very much for your feedback and the code!

I just saw your PR and it got me thinking about the interface of this library.

After reflection I decided to rewrite this gem to simplify the matching and keep the language tags at the exact same cases as the case used by the server.

I hope this resolves the bug that you kindly reported. Sorry for not having just merged your work which I appreciate by the way.

I close this PR, but feel free to open another one if needed.

**Comment by pond** [comment]
This looks like it might work though I need to investigate what the removal of `:two_letter_truncate` will mean to our application, which used this for a fallback from specific to more general matching. The gem perhaps does this automatically now.

Unfortunately I can't try it out - the gem now requires Ruby 3. We are on 2.7 and are not yet able/willing to move to Ruby 3, so we're stuck on v1. Would it be possible to perhaps release a v2.0.1 which relaxed this Ruby requirement, please?

(Later edit: Looking at the commit, the Ruby 3 requirement seems pretty deliberate so if you're not minded to re-introduce support for 2.7.x, or if the gem's using Ruby 3-specific features, that's OK; I'll just have to wait until we've moved over to Ruby 3 ourselves 😄)

**Comment by cyril** [comment]
> Would it be possible to perhaps release a v2.0.1 which relaxed this Ruby requirement

Yes sure. I just updated the code and the gem. Thank you for using it. 😀

**Comment by pond** [comment]
That's awesome 🙂 thanks. I've updated our code base accordingly.

**Pull request closed without merging**
